#+TITLE:  Entering Adulthood
#+DATE:   Winter, 2020

* Introduction

* Day 1: Taking the Precepts

  To begin, wake up at 4:30. This will be your wake-up time for the rest of your
  life.

  Read the following five precepts aloud. Dedicating your efforts to them for
  your top priority as a grown-up.
  

** Take the Precepts

*** Reverence for Life:

    Aware of the suffering caused by the destruction of life, I am committed to
    cultivating the insight of interbeing and compassion and learning ways to
    protect the lives of people, animals, plants, and minerals. I am determined
    not to kill, not to let others kill, and not to support any act of killing
    in the world, in my thinking, or in my way of life. Seeing that harmful
    actions arise from anger, fear, greed, and intolerance, which in turn come
    from dualistic and discriminative thinking, I will cultivate openness,
    non-discrimination, and non-attachment to views in order to transform
    violence, fanaticism, and dogmatism in myself and in the world.

*** True Happiness:

    Aware of the suffering caused by exploitation, social injustice, stealing,
    and oppression, I am committed to practicing generosity in my thinking,
    speaking, and acting. I am determined not to steal and not to possess
    anything that should belong to others; and I will share my time, energy, and
    material resources with those who are in need. I will practice looking
    deeply to see that the happiness and suffering of others are not separate
    from my own happiness and suffering; that true happiness is not possible
    without understanding and compassion; and that running after wealth, fame,
    power and sensual pleasures can bring much suffering and despair. I am aware
    that happiness depends on my mental attitude and not on external conditions,
    and that I can live happily in the present moment simply by remembering that
    I already have more than enough conditions to be happy. I am committed to
    practicing Right Livelihood so that I can help reduce the suffering of
    living beings on Earth and stop contributing to climate change.
        
*** True Love:

    Aware of the suffering caused by sexual misconduct, I am committed to
    cultivating responsibility and learning ways to protect the safety and
    integrity of individuals, couples, families, and society. Knowing that
    sexual desire is not love, and that sexual activity motivated by craving
    always harms myself as well as others, I am determined not to engage in
    sexual relations without true love and a deep, long-term commitment made
    known to my family and friends. I will do everything in my power to protect
    children from sexual abuse and to prevent couples and families from being
    broken by sexual misconduct. Seeing that body and mind are one, I am
    committed to learning appropriate ways to take care of my sexual energy and
    cultivating loving kindness, compassion, joy and inclusiveness – which are
    the four basic elements of true love – for my greater happiness and the
    greater happiness of others. Practicing true love, we know that we will
    continue beautifully into the future.

*** Loving Speech and Deep Listening:

    Aware of the suffering caused by unmindful speech and the inability to
    listen to others, I am committed to cultivating loving speech and
    compassionate listening in order to relieve suffering and to promote
    reconciliation and peace in myself and among other people, ethnic and
    religious groups, and nations. Knowing that words can create happiness or
    suffering, I am committed to speaking truthfully using words that inspire
    confidence, joy, and hope. When anger is manifesting in me, I am determined
    not to speak. I will practice mindful breathing and walking in order to
    recognize and to look deeply into my anger. I know that the roots of anger
    can be found in my wrong perceptions and lack of understanding of the
    suffering in myself and in the other person. I will speak and listen in a
    way that can help myself and the other person to transform suffering and see
    the way out of difficult situations. I am determined not to spread news that
    I do not know to be certain and not to utter words that can cause division
    or discord. I will practice Right Diligence to nourish my capacity for
    understanding, love, joy, and inclusiveness, and gradually transform anger,
    violence, and fear that lie deep in my consciousness.
        
*** Nourishment and Healing:

    Aware of the suffering caused by unmindful consumption, I am committed to
    cultivating good health, both physical and mental, for myself, my family,
    and my society by practicing mindful eating, drinking, and consuming. I will
    practice looking deeply into how I consume the Four Kinds of Nutriments,
    namely edible foods, sense impressions, volition, and consciousness. I am
    determined not to gamble, or to use alcohol, drugs, or any other products
    which contain toxins, such as certain websites, electronic games, TV
    programs, films, magazines, books, and conversations. I will practice coming
    back to the present moment to be in touch with the refreshing, healing and
    nourishing elements in me and around me, not letting regrets and sorrow drag
    me back into the past nor letting anxieties, fear, or craving pull me out of
    the present moment. I am determined not to try to cover up loneliness,
    anxiety, or other suffering by losing myself in consumption. I will
    contemplate interbeing and consume in a way that preserves peace, joy, and
    well-being in my body and consciousness, and in the collective body and
    consciousness of my family, my society and the Earth.

   Speak the precepts every morning upon awaking. Eventually, after weeks of
   repetition, you will have them memorized.

** Put on the bracelet

   The bone-bracelet is a symbol of your commitment to being a true human being.
   I reminds you that you have a precious short amount of time on this earth,
   that every day is a miracle, and that you have committed to living by the
   five precepts.

   The bracelet comes off only at night when going to bed, then it is to be worn
   again the following morning after reciting the precepts.

** Daily Schedule

   Your days will have a familiar routine.

*** Weekends
    
    04:30  Wake Up, speak the precepts, dress
    04:45  Study the texts
    05:00  Sitting Practice
    05:30  Green Tea, read news, review calendar and set daily goals
    06:30  Walk the dog
    07:00  Household chores
    12:00  Green Tea, read or write for fun
    13:00  Professional work
    15:00  Exercise
    17:00  Prepare dinner
    18:30  Eat dinner
    19:30  Family time
    21:00  Green tea, journal writing
    21:45  Lights out

*** Week days
    
    04:30  Wake Up, speak the precepts, dress
    04:45  Study the texts
    05:00  Sitting Practice
    05:30  Green Tea, read news, review calendar and set daily goals
    06:30  Walk the dog
    07:00  Household chores
    07:30  Professional work
    15:00  Exercise
    17:00  Prepare dinner
    18:30  Eat dinner
    19:30  Family time
    21:00  Green tea, journal writing
    21:45  Lights out

** Exercise

   Exercise should be a pleasurable experience of understanding and experiencing
   the strength, speed, and endurance of your body. This is not a breaking-down
   to make stronger, but a celebrataion of ability and the experience of meeting
   a challenge. If exercise becomes suffering, sitting practice should be
   substituted.

*** Warm-Up Walk

*** Two-Mile Run

    Do a combination of running and walking until the entire two miles can be
    achieved.

*** A-Days: Calisthenics

**** Jump Rope

     10 minutes continuous jump rope
    
**** Pull-up Practice

     If you can't do more than one pull-up:
     - 60 seconds of negatives throughout the day
     - 6 ladders 3, 5, 7-second negatives

**** Bodyweight Squats

     - 100 squats in a row

**** Push-up Practice

     - 6 sets of 12 push-ups

**** Sit-ups

     - 100 sit-ups in a row

*** B-Days: Running

    Choose one of the following:
    
**** Sprints: 5x small hill, 3x large hill

**** Distance: Run 2 - 4 miles in addition to warm-up run     
