#+TITLE:  Guide to Tranforming into an Adult
#+AUTHOR: Richard Cuminale
#+DATE:   2020-12-03 to ...

* Introduction
  I'm really not sure how to begin, except to write that I never became an adult.
  There's an unbroken string of days from my beginning as a child in elementary school all the way until now, and I haven't changed.
I remain, in other words, a child.
Looking for a guide to becoming an adult, I couldn't find anything concrete.
Nothing that said, "today, do this," and "tomorrow, plan for that."
I found either stories of others who had become adults or vague advice about how to be healther and more responsible.
Since there are no good guides out there, I decided to make my own.

This is a guide that I am writing as I transform. 
I will be making small, but consistent steps every day until I reach a point where I have transformed from a child to an adult.
These steps will be a variety of different kinds of things, but the picture they build should be reasonably cohesive.
Most importantly, Ill know that once I have completed this guide, not only will I know that I have attained my goal, but I will also have set a light to the path for others.

I write this for my sons, Andrew and Jack.
I will smile if they get to read this someday.

* Day 1: The Five Precepts

  The most important part of being an adult is taking the five precepts and committing to living an ethical life, promoting well-being in yourself and others. Day one means committing to:

1. Aware of the suffering caused by the destruction of life, I am committed to cultivating the insight of interbeing and compassion, and learning ways to protect the lives of people, animals, plants, and minerals. I am determined not to kill, not to let others kill, and not to support any act of killing in the world, in my thinking, or in my way of life. Seeing that harmful actions arise from anger, fear, greed, and intolerance, which in turn come from dualistic and discriminative thinking, I will cultivate openness, non-discrimination, and non-attachment to views in order to transform violence, fanaticism, and dogmatism in myself and in the world.
